---
- name: Instalar httpd
  apt:
    name: apache2
    state: latest

- name: Start e enable o servico httpd
  service:
    name: apache2
    state: started
    enabled: true

- name: Verificar se o diretoio vhost esta presente
  file:
    path: "/var/www/vhosts/{{ ansible_hostname }}"
    state: directory

- name: Entregar conteúdo html
  copy:
    src: index.html
    dest: "/var/www/vhosts/{{ ansible_hostname }}"

- name: Template arquivo vhost
  template:
    src: vhost.conf.j2
    dest: /etc/apache2/conf.a/vhost.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart_httpd        