---
- name: Manage apache2.conf
  hosts: web
  become: yes
  tasks:
  - name: Copiar arquivo de configuracao do Apache
    copy:
      src: apache2.conf
      dest: /etc/apache2/
    notify:
        - restart_apache
  handlers:
    - name: restart_apache
      service:
        name: apache2
        state: restarted