---
- name: Garantir usuarios
  hosts: node1
  become: yes

  tasks:
    - name: Garantir a presenca de tres usuarios
      user:
        name: "{{ item.username }}"
        state: present
        groups: "{{ item.groups }}"
      loop:
        - { username: 'dev_user', groups: 'ftp' }
        - { username: 'qa_user', groups: 'ftp' }
        - { username: 'prod_user', groups: 'apache' }