
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.boot_timeout = 600 # wait max 10 minutes
  config.ssh.username = 'vagrant'
  config.ssh.password = 'vagrant'
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |v|
	v.memory = 1024
  end

  config.vm.define "node1" do |m|
	m.vm.network "private_network", ip: "172.17.177.40"
  end
  config.vm.define "node2" do |m|
    m.vm.network "private_network", ip: "172.17.177.42"
  end

  config.vm.define "node3" do |m|
    m.vm.network "private_network", ip: "172.17.177.44"
  end
end


