---
- name: Apache server instalado
  hosts: web
  become: yes
  tasks:
  - name: Ultima versao do apache server instalado
    apt: name=apache2 update_cache=yes state=latest
  - name: Apache started e enable
    service:
      name: apache2
      enabled: true
      state: started    
  - name: Copiar web.html
    copy:
      src: /home/handerson/repositorioGitHub/devops/ansible/workshop-redhat/ansible-files/web.html
      dest: /var/www/html/index.html      